### ISSUE TITLE
About License Terms

### ISSUE THREAD

**Issue by isurugit** [codrops/ScatteredPolaroidsGallery#8]
Hi,

I visited your plugins live demo. It is a cool fantastic plugin. I'm bit confused with the license term "as-is". I'm developing a WordPress premium theme. I would like to make a shortcode for displaying WordPress post thumbnails integrating with your plugin. I do not use & redistribute your code directly as it is.  Is it possible to achieve my goal?. I do not like to violate any License terms & conditions for any reason.That's why I ask this from you directly.  I'm happy to know your thought about this & waiting a positive feedback. 

Thanks.

**Comment by crnacura** [comment]
Hi, if you integrate this in your theme that you are going to sell, then you are not selling the resources as-is but as part of your work. That's completely fine and you are not violating our license. 
Thanks, ML
